server:
  port: ${APP_PORT:8080}
  servlet:
    application-display-name: MyAPP


logging:
  level:
    ROOT: INFO
    ru.innopolis: DEBUG

info:
  app:
    name: Actuator Demo Test
    version: 0.0.1
    description: Spring Boot Demo

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  metrics:
    export:
      atlas:
        enabled: true

---

spring:
  profiles: local
  
server:
  port: ${APP_PORT:9091}
  servlet:
    application-display-name: MyAPP